### ISSUE TITLE
IncitoWebView submodule missing

### ISSUE THREAD

**Issue by SValchyshyn** [tjek/incito-ios#15]
Hi! I have faced an issue with missing `https://github.com/shopgun/incito-webview.git` while I fetch my `tjek-swift-sdk` dependency. 

It seems like `incito-webview.git` is giving me 404, so maybe you have removed something extra?

**Comment by mortenbo** [comment]
@SValchyshyn Sorry about that, it should work again now.

**Comment by SValchyshyn** [comment]
Yes, I confirm. Thank you 👍
